// ============================================================================
// Kits de regalo Fiestas Patrias 2026 — 15 combinaciones oficiales.
// Cada kit combina productos reales del catálogo PEYU (100% reciclado).
// tag: 'Casa' | 'Regalo' | 'Empresa'. Los kits Empresa se cotizan (desde 20u).
// ============================================================================

export const KITS_FIESTAS = [
  {
    id: 'dieciochero-clasico',
    nombre: 'Kit Dieciochero Clásico',
    emoji: '🇨🇱',
    tag: 'Casa',
    desc: 'Lo esencial para partir el 18 con identidad chilena en la mesa.',
    incluye: ['1 Cacho de dados reciclado', 'Set de 4 posavasos', '1 Llavero PEYU'],
    precio: 19990,
    destacado: true,
  },
  {
    id: 'asado-maestro',
    nombre: 'Kit Asado Maestro',
    emoji: '🔥',
    tag: 'Casa',
    desc: 'Para el parrillero de la casa: todo lo que rodea al asado, en reciclado.',
    incluye: ['1 Cacho premium grabado', 'Set de 6 posavasos', '1 Organizador de mesa'],
    precio: 29990,
    destacado: true,
  },
  {
    id: 'cacho-y-amigos',
    nombre: 'Kit Cacho & Amigos',
    emoji: '🎲',
    tag: 'Casa',
    desc: 'Dos cachos con dados para que el dudo no pare en toda la semana.',
    incluye: ['2 Cachos con dados', 'Grabado láser con nombres (opcional)'],
    precio: 24990,
  },
  {
    id: 'mesa-chilena',
    nombre: 'Kit Mesa Chilena',
    emoji: '🍽️',
    tag: 'Casa',
    desc: 'Viste tu mesa dieciochera con piezas marmoladas únicas.',
    incluye: ['Set de 6 posavasos', '2 Bandejas / organizadores de mesa'],
    precio: 17990,
  },
  {
    id: 'terraza-patria',
    nombre: 'Kit Terraza Patria',
    emoji: '🌿',
    tag: 'Casa',
    desc: 'Verde de verdad: maceteros reciclados para la terraza del 18.',
    incluye: ['2 Maceteros medianos', 'Set de 4 posavasos'],
    precio: 22990,
  },
  {
    id: 'playa-dieciochera',
    nombre: 'Kit Playa Dieciochera',
    emoji: '🏖️',
    tag: 'Casa',
    desc: 'Para los que celebran el 18 en la costa: paletas todo terreno.',
    incluye: ['Set de paletas recicladas', 'Pelota', '1 Llavero PEYU'],
    precio: 15990,
  },
  {
    id: 'familiar-completo',
    nombre: 'Kit Familiar Completo',
    emoji: '👨‍👩‍👧‍👦',
    tag: 'Casa',
    desc: 'El kit grande: juegos y mesa para toda la familia en un solo pack.',
    incluye: ['1 Cacho con dados', 'Set de paletas', 'Set de 6 posavasos', '1 Llavero'],
    precio: 34990,
    destacado: true,
  },
  {
    id: 'escritorio-patrio',
    nombre: 'Kit Escritorio Patrio',
    emoji: '✏️',
    tag: 'Regalo',
    desc: 'Vuelve a la pega después del 18 con un escritorio con identidad.',
    incluye: ['1 Organizador de escritorio', '1 Portalápices grabado'],
    precio: 14990,
  },
  {
    id: 'regalo-verde',
    nombre: 'Kit Regalo Verde',
    emoji: '🪴',
    tag: 'Regalo',
    desc: 'Un regalo sustentable que dura: macetero + carcasa reciclada.',
    incluye: ['1 Macetero mediano', '1 Carcasa de celular a elección'],
    precio: 19990,
  },
  {
    id: 'tech-chileno',
    nombre: 'Kit Tech Chileno',
    emoji: '📱',
    tag: 'Regalo',
    desc: 'Carcasa marmolada única + grabado láser personalizado.',
    incluye: ['1 Carcasa (elige tu modelo)', 'Grabado láser personalizado', '1 Llavero'],
    precio: 16990,
  },
  {
    id: 'parejas',
    nombre: 'Kit Parejas',
    emoji: '💚',
    tag: 'Regalo',
    desc: 'Dos carcasas marmoladas grabadas — ninguna es igual a otra.',
    incluye: ['2 Carcasas a elección', 'Grabado láser en ambas'],
    precio: 21990,
  },
  {
    id: 'anfitrion',
    nombre: 'Kit Anfitrión',
    emoji: '🥂',
    tag: 'Regalo',
    desc: 'El regalo perfecto para quien pone la casa este 18.',
    incluye: ['1 Cacho premium', 'Set de 6 posavasos', 'Grabado con frase (opcional)'],
    precio: 26990,
  },
  {
    id: 'corporativo-esencial',
    nombre: 'Kit Corporativo Esencial',
    emoji: '🏢',
    tag: 'Empresa',
    desc: 'El clásico corporativo del 18: cacho con el logo de tu empresa.',
    incluye: ['1 Cacho con dados', '1 Llavero', 'Grabado láser con tu logo', 'Tarjeta de saludo'],
    precio: 12990,
    porUnidad: true,
    minimo: 20,
  },
  {
    id: 'corporativo-premium',
    nombre: 'Kit Corporativo Premium',
    emoji: '⭐',
    tag: 'Empresa',
    desc: 'Para clientes clave: piezas premium grabadas con tu marca.',
    incluye: ['1 Cacho premium', '1 Organizador de escritorio', 'Grabado láser con tu logo', 'Packaging kraft'],
    precio: 25000,
    porUnidad: true,
    minimo: 20,
    destacado: true,
  },
  {
    id: 'corporativo-full-18',
    nombre: 'Kit Corporativo Full 18',
    emoji: '🎁',
    tag: 'Empresa',
    desc: 'El kit completo para regalar identidad chilena a todo tu equipo.',
    incluye: ['1 Cacho con dados', 'Set de paletas', 'Set de 4 posavasos', 'Grabado láser con tu logo', 'Packaging premium'],
    precio: 35000,
    porUnidad: true,
    minimo: 20,
  },
];

export const TAGS_KITS = ['Todos', 'Casa', 'Regalo', 'Empresa'];

export const waLinkKit = (kit) => {
  const msg = `Hola PEYU 🇨🇱, quiero el ${kit.nombre} de Fiestas Patrias (${kit.porUnidad ? `desde ${kit.minimo}u` : '1 kit'}).`;
  return `https://wa.me/56935040242?text=${encodeURIComponent(msg)}`;
};