// Catálogo completo de propuestas de design system PEYU 2026
// presentadas a los fundadores. Cada propuesta tiene un mecanismo
// de conversión distinto y se prueba en sesión.

export const FOUNDERS_LAYOUTS = [
  // ─── RONDA 1 · PEYU LIQUID 2026 ─────────────────────────────────
  {
    id: 'liquid-forest',
    round: 1,
    label: 'Liquid Forest',
    subtitle: 'Verde nocturno · Glass dark',
    image: 'https://media.base44.com/images/public/69d99b9d61f699701129c103/269069e45_generated_c91089fb.png',
    typography: 'Fraunces serif italic + Plus Jakarta Sans',
    palette: ['#020617', '#0F8B6C', '#22D3EE', '#D96B4D'],
    mechanism: 'Glass nocturno con orbes verde-cyan + acento terracota',
    cvr: 'Alto B2C',
    bestFor: 'Marca premium nocturna, mood futurista-orgánico',
    aesthetic: 'Bosque digital nocturno, Apple iOS 26 + Aesop',
  },
  {
    id: 'liquid-aurora',
    round: 1,
    label: 'Liquid Aurora',
    subtitle: 'Crema día · Glass light',
    image: 'https://media.base44.com/images/public/69d99b9d61f699701129c103/0b0cdaeb9_generated_282922dd.png',
    typography: 'Fraunces serif + Plus Jakarta Sans',
    palette: ['#F7F2EA', '#0F8B6C', '#A7D9C9', '#D96B4D'],
    mechanism: 'Glass blanco translúcido sobre crema + verde sólido',
    cvr: 'Alto B2C+B2B',
    bestFor: 'E-commerce premium chileno de día, cálido pero moderno',
    aesthetic: 'Aesop-meets-tech, premium consciente',
  },
  {
    id: 'liquid-dual',
    round: 1,
    label: 'Liquid Dual',
    subtitle: 'Día+Noche auto adaptativo',
    image: 'https://media.base44.com/images/public/69d99b9d61f699701129c103/56d4a6a0e_generated_707636ca.png',
    typography: 'Fraunces variable + Plus Jakarta Sans',
    palette: ['#FFFFFF', '#020617', '#0F8B6C', '#D96B4D'],
    mechanism: 'Sistema dual auto light/dark con toggle distintivo',
    cvr: 'Alto general',
    bestFor: 'Design system maduro tipo Linear/Vercel, profesional',
    aesthetic: 'Apple iOS 26 vibe, sistema único y reconocible',
  },
  {
    id: 'liquid-editorial',
    round: 1,
    label: 'Liquid Editorial',
    subtitle: 'Magazín vivo de lujo',
    image: 'https://media.base44.com/images/public/69d99b9d61f699701129c103/9965352aa_generated_ef83692e.png',
    typography: 'Fraunces italic GIGANTE + Plus Jakarta Sans',
    palette: ['#FAFAF7', '#0F8B6C', '#000000', '#D96B4D'],
    mechanism: 'Hero serif italic clamp 4-7rem estilo Vogue',
    cvr: 'Medio-alto B2C premium',
    bestFor: 'Brand-first storytelling, lujo consciente chileno',
    aesthetic: 'Revista de lujo consciente, editorial premium',
  },

  // ─── RONDA 2 · CONVERSIÓN MULTI-AGÉNTICA ────────────────────────
  {
    id: 'agent-cockpit',
    round: 2,
    label: 'Agent Cockpit',
    subtitle: 'Split persistente con IA',
    image: 'https://media.base44.com/images/public/69d99b9d61f699701129c103/af8c55c3d_generated_0df1479f.png',
    typography: 'Plus Jakarta Sans bold + Inter',
    palette: ['#020617', '#0F8B6C', '#22D3EE', '#D96B4D'],
    mechanism: 'Agente IA siempre visible 40% pantalla — sigue al usuario',
    cvr: '+59% growth (Adobe holiday 2025)',
    bestFor: 'Conversión multi-agéntica B2C+B2B unified',
    aesthetic: 'Copiloto productividad shopping',
  },
  {
    id: 'voice-first',
    round: 2,
    label: 'Voice-First Holographic',
    subtitle: 'Conversación por voz',
    image: 'https://media.base44.com/images/public/69d99b9d61f699701129c103/dae3d3c06_generated_30e49698.png',
    typography: 'Fraunces italic dramático + Plus Jakarta Sans',
    palette: ['#F7F2EA', '#0F8B6C', '#22D3EE', '#D96B4D'],
    mechanism: 'Botón record gigante voice+text reduce fricción a cero',
    cvr: 'Alto mobile (voice-first nativo)',
    bestFor: 'Captura intent inmediato, accesibilidad premium',
    aesthetic: 'Futurista accesible, conversación humana',
  },
  {
    id: 'multi-agent-theater',
    round: 2,
    label: 'Multi-Agent Theater',
    subtitle: 'Equipo IA visible en vivo',
    image: 'https://media.base44.com/images/public/69d99b9d61f699701129c103/2dfdf87cb_generated_6aea0502.png',
    typography: 'JetBrains Mono + Plus Jakarta + Fraunces',
    palette: ['#020617', '#0F8B6C', '#A78BFA', '#22D3EE', '#D96B4D'],
    mechanism: '4 avatares IA visibles trabajando en vivo + activity ticker',
    cvr: 'Trust + transparencia = alto B2B',
    bestFor: 'Diferenciación vs competidores, prueba social',
    aesthetic: 'Oficina virtual transparente, AI fleet showcase',
  },
  {
    id: 'smart-surface',
    round: 2,
    label: 'Smart Surface AI',
    subtitle: 'Layout adaptativo por contexto',
    image: 'https://media.base44.com/images/public/69d99b9d61f699701129c103/b3c5af02f_generated_d08a79ce.png',
    typography: 'Plus Jakarta Sans variable + Fraunces',
    palette: ['#FFFFFF', '#020617', '#0F8B6C', '#D96B4D'],
    mechanism: 'Layout muta según UTM/hora/intent — cada visita es única',
    cvr: 'Máximo: home perfecta para cada visitante',
    bestFor: 'AI-native end-to-end, web inteligente',
    aesthetic: 'Web que sabe quién eres',
  },

  // ─── RONDA 3 · ALTERNATIVAS RADICALES ───────────────────────────
  {
    id: 'spatial-3d',
    round: 3,
    label: 'Spatial 3D',
    subtitle: 'Vision Pro vibe · Three.js',
    image: 'https://media.base44.com/images/public/69d99b9d61f699701129c103/e23ce8a58_generated_3c63d052.png',
    typography: 'SF Pro Display + Plus Jakarta Sans',
    palette: ['#0A0A1A', '#0F8B6C', '#22D3EE', '#A78BFA'],
    mechanism: 'Profundidad 3D real con Three.js — orbes producto rotables',
    cvr: 'Alto retención (WOW factor)',
    bestFor: 'Brand premium tech-forward, diferenciación máxima',
    aesthetic: 'Apple Vision Pro web, futuro tangible',
  },
  {
    id: 'generative-canvas',
    round: 3,
    label: 'Generative Canvas',
    subtitle: 'IA pinta la web en vivo',
    image: 'https://media.base44.com/images/public/69d99b9d61f699701129c103/52fefb4d0_generated_c5774a40.png',
    typography: 'Fraunces serif EXTRA grande + Inter mono',
    palette: ['#FAFAF7', '#0F8B6C', '#000000', '#D96B4D'],
    mechanism: 'Input prompt central tipo ChatGPT/Midjourney/Linear',
    cvr: 'Alto multi-agente (UX ya familiar)',
    bestFor: 'AI-native maximal, conversión inmediata',
    aesthetic: 'Web-as-canvas, art-meets-AI',
  },
  {
    id: 'bento-grid-pro',
    round: 3,
    label: 'Bento Grid Pro',
    subtitle: 'Apple-style modular',
    image: 'https://media.base44.com/images/public/69d99b9d61f699701129c103/fec96b6f3_generated_030b5234.png',
    typography: 'Plus Jakarta Sans + Inter mono',
    palette: ['#F7F2EA', '#020617', '#0F8B6C', '#D96B4D'],
    mechanism: '8-12 cards modulares — zero scroll, todo arriba del fold',
    cvr: 'Alto: máximo CTA visible',
    bestFor: 'Densidad informativa premium, B2B+B2C balance',
    aesthetic: 'Apple iCloud / Linear pricing',
  },
  {
    id: 'scrollytelling',
    round: 3,
    label: 'Scrollytelling Cinemato',
    subtitle: 'Awwwards SOTD experience',
    image: 'https://media.base44.com/images/public/69d99b9d61f699701129c103/28519ccdb_generated_3399b375.png',
    typography: 'Fraunces italic GIGANTE animado + Plus Jakarta',
    palette: ['#020617', '#0F8B6C', '#F7F2EA', '#D96B4D'],
    mechanism: 'Scroll cinematográfico GSAP — secciones full-screen',
    cvr: 'Alto premium B2C',
    bestFor: 'Brand storytelling máximo, lujo cinéfilo',
    aesthetic: 'Awwwards SOTD, brand-first conversion',
  },

  // ─── RONDA 4 · EVOLUCIÓN ABSOLUTA (10 nuevas) ───────────────────
  {
    id: 'living-earth',
    round: 4,
    label: 'Living Earth OS',
    subtitle: 'Tierra viva · Bio-luminiscente',
    image: 'https://media.base44.com/images/public/69d99b9d61f699701129c103/111597876_generated_image.png',
    typography: 'Fraunces serif italic + Plus Jakarta Sans',
    palette: ['#F5EFE6', '#1B4332', '#52B788', '#D96B4D'],
    mechanism: 'AI orb pulsante con partículas bio-luminiscentes verdes',
    cvr: 'Alto eco-consciente B2C',
    bestFor: 'Brand sustentable como valor #1',
    aesthetic: 'Aesop x OpenAI, lujo sustentable cálido',
  },
  {
    id: 'quantum-chat-grid',
    round: 4,
    label: 'Quantum Chat Grid',
    subtitle: 'Comando Linear/Raycast',
    image: 'https://media.base44.com/images/public/69d99b9d61f699701129c103/3cc9baf60_generated_image.png',
    typography: 'JetBrains Mono + Plus Jakarta Sans bold',
    palette: ['#0A0E27', '#10B981', '#06B6D4', '#D96B4D'],
    mechanism: 'Command bar central + bento de agentes IA en vivo',
    cvr: 'Máximo B2B tech-forward',
    bestFor: 'Empresas tech, productividad shopping',
    aesthetic: 'Linear meets ChatGPT, AI-native SaaS',
  },
  {
    id: 'atelier-material',
    round: 4,
    label: 'Atelier Material',
    subtitle: 'Editorial manufacturera',
    image: 'https://media.base44.com/images/public/69d99b9d61f699701129c103/dd36a79b1_generated_image.png',
    typography: 'Fraunces italic GIGANTE + Plus Jakarta',
    palette: ['#FAF6F0', '#1B4332', '#A7D9C9', '#D96B4D'],
    mechanism: 'Showcase 3D del material reciclándose en producto',
    cvr: 'Alto B2C premium consciente',
    bestFor: 'Transparencia manufacturera = valor de marca',
    aesthetic: 'COS x Hermès Atelier, editorial premium',
  },
  {
    id: 'neon-mercado',
    round: 4,
    label: 'Neón Mercado',
    subtitle: 'Cyber-Latino energía Chile',
    image: 'https://media.base44.com/images/public/69d99b9d61f699701129c103/262ee8141_generated_image.png',
    typography: 'Plus Jakarta bold + acentos Mapuche SVG',
    palette: ['#1A1A2E', '#10B981', '#FF6B35', '#FFD700'],
    mechanism: 'Activity feed live + neon glows + identidad chilena',
    cvr: 'Máximo masivo B2C latam',
    bestFor: 'Energía Mercado Libre + identidad cultural',
    aesthetic: 'Mercado Libre 2030 meets cyberpunk Santiago',
  },
  {
    id: 'garden-studio',
    round: 4,
    label: 'Garden Studio',
    subtitle: 'Vivario digital · Biomimicry',
    image: 'https://media.base44.com/images/public/69d99b9d61f699701129c103/67f33c63a_generated_image.png',
    typography: 'Fraunces elegante + Plus Jakarta Sans',
    palette: ['#E8F5E9', '#1B5E20', '#A5D6A7', '#D96B4D'],
    mechanism: 'Chat AI como terrario vivo con productos como plantas',
    cvr: 'Alto B2C emocional',
    bestFor: 'Conexión emocional con sustentabilidad',
    aesthetic: 'Aesop x Studio Ghibli x Apple iOS 26',
  },
  {
    id: 'mission-control',
    round: 4,
    label: 'Mission Control',
    subtitle: 'HUD profesional B2B',
    image: 'https://media.base44.com/images/public/69d99b9d61f699701129c103/7a4cc9684_generated_image.png',
    typography: 'JetBrains Mono + Plus Jakarta Sans',
    palette: ['#000000', '#10B981', '#06B6D4', '#D96B4D'],
    mechanism: 'Dashboard HUD multi-panel — pipeline + agentes + radar',
    cvr: 'Máximo B2B corporativo',
    bestFor: 'Empresas grandes, compras pro',
    aesthetic: 'NASA Mission Control + Stripe Dashboard',
  },
  {
    id: 'liquid-metal',
    round: 4,
    label: 'Liquid Metal Sculpture',
    subtitle: 'Apple Keynote reveal',
    image: 'https://media.base44.com/images/public/69d99b9d61f699701129c103/1e4dded97_generated_image.png',
    typography: 'Fraunces italic display + Plus Jakarta',
    palette: ['#F5F5F0', '#1B4332', '#C0C0C0', '#D96B4D'],
    mechanism: '3D hero cinematográfico de plástico → producto',
    cvr: 'Alto wow factor + premium B2C',
    bestFor: 'Lanzamiento producto, brand showcase',
    aesthetic: 'Apple Keynote x Bang&Olufsen x Aesop',
  },
  {
    id: 'conversational-storefront',
    round: 4,
    label: 'Conversational Storefront',
    subtitle: 'Chat sincronizado con canvas',
    image: 'https://media.base44.com/images/public/69d99b9d61f699701129c103/96c3f0970_generated_image.png',
    typography: 'Fraunces italic + Plus Jakarta Sans',
    palette: ['#FAFAF7', '#0F8B6C', '#A7D9C9', '#D96B4D'],
    mechanism: 'Conversación 40% + canvas productos 60% sincronizado',
    cvr: 'Máximo conversion-as-conversation',
    bestFor: 'Multi-agéntica nativa, AI-first commerce',
    aesthetic: 'Linear x Notion x Stripe',
  },
  {
    id: 'holographic-atelier',
    round: 4,
    label: 'Holographic Atelier',
    subtitle: 'Showroom espacial · Vision Pro',
    image: 'https://media.base44.com/images/public/69d99b9d61f699701129c103/338389cc7_generated_image.png',
    typography: 'Fraunces italic GIGANTE + Plus Jakarta',
    palette: ['#0F1B2E', '#5EEAD4', '#A78BFA', '#D96B4D'],
    mechanism: 'Productos holográficos flotantes + AI ribbon de luz',
    cvr: 'Máximo wow + B2C premium',
    bestFor: 'Diferenciación radical, brand del futuro',
    aesthetic: 'Apple Vision Pro x Blade Runner 2049',
  },
  {
    id: 'origami-folded',
    round: 4,
    label: 'Origami Folded',
    subtitle: 'Papel doblado · Craft japonés',
    image: 'https://media.base44.com/images/public/69d99b9d61f699701129c103/81f048f94_generated_image.png',
    typography: 'Fraunces italic + Plus Jakarta Sans',
    palette: ['#FFFFFF', '#1B4332', '#A7D9C9', '#D96B4D'],
    mechanism: 'UI como papel origami con sombras suaves + AI grulla',
    cvr: 'Alto B2C consciente premium',
    bestFor: 'Mindful luxury, narrativa craft',
    aesthetic: 'Muji x Aesop x Studio Wieki Somers',
  },
];

export const ROUND_INFO = {
  1: { name: 'PEYU Liquid 2026', desc: 'Cohesión Apple iOS 26 + identidad PEYU' },
  2: { name: 'Conversión Multi-Agéntica', desc: 'Mecanismos validados +31% CVR (Adobe 2026)' },
  3: { name: 'Alternativas Radicales', desc: 'Diferenciación máxima vs competidores' },
  4: { name: 'Evolución Absoluta', desc: 'Cohesión digital + eco + B2C/B2B premium' },
};