import { createClientFromRequest } from 'npm:@base44/sdk@0.8.23';

Deno.serve(async (req) => {
  const base44 = createClientFromRequest(req);
  const user = await base44.auth.me();
  if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

  const pedidos = [
    { numero_pedido: 'PW-001', fecha: '2026-04-01', canal: 'Web Propia', cliente_nombre: 'María González', cliente_email: 'maria@gmail.com', cliente_telefono: '+56912345678', tipo_cliente: 'B2C Individual', sku: 'SOPC-001', descripcion_items: '2x Soporte Celular PEYU', cantidad: 2, subtotal: 13980, costo_envio: 3990, descuento: 0, total: 17970, medio_pago: 'WebPay', estado: 'Entregado', ciudad: 'Santiago', courier: 'Chilexpress', calificacion_cliente: 5, notas: 'Llegó perfecto' },
    { numero_pedido: 'PW-002', fecha: '2026-04-02', canal: 'Instagram', cliente_nombre: 'Carlos Muñoz', cliente_email: 'carlos@hotmail.com', cliente_telefono: '+56987654321', tipo_cliente: 'B2C Individual', sku: 'LLAV-001', descripcion_items: '5x Llavero Soporte Celular personalizado', cantidad: 5, subtotal: 19950, costo_envio: 3990, descuento: 0, total: 23940, medio_pago: 'Transferencia', estado: 'Entregado', ciudad: 'Valparaíso', courier: 'Starken', requiere_personalizacion: true, texto_personalizacion: 'CMuñoz 2026', calificacion_cliente: 4 },
    { numero_pedido: 'PW-003', fecha: '2026-04-03', canal: 'WhatsApp', cliente_nombre: 'Empresa TechSolve SpA', cliente_email: 'compras@techsolve.cl', cliente_telefono: '+56222334455', tipo_cliente: 'B2B Corporativo', sku: 'KIT-ESCR-001', descripcion_items: '20x Kit Escritorio Corporativo con logo', cantidad: 20, subtotal: 399800, costo_envio: 0, descuento: 20000, total: 379800, medio_pago: 'Transferencia', estado: 'En Producción', ciudad: 'Santiago', courier: 'BlueExpress', requiere_personalizacion: true, texto_personalizacion: 'Logo TechSolve', logo_recibido: true },
    { numero_pedido: 'PW-004', fecha: '2026-04-04', canal: 'Shopify', cliente_nombre: 'Ana Rodríguez', cliente_email: 'ana.rodriguez@gmail.com', cliente_telefono: '+56945678901', tipo_cliente: 'B2C Individual', sku: 'LAMP-001', descripcion_items: '1x Lámpara Chillka', cantidad: 1, subtotal: 23490, costo_envio: 3990, descuento: 0, total: 27480, medio_pago: 'Débito', estado: 'Despachado', ciudad: 'Concepción', courier: 'Chilexpress', tracking: 'CHL9087654' },
    { numero_pedido: 'PW-005', fecha: '2026-04-05', canal: 'Web Propia', cliente_nombre: 'Pedro Martínez', cliente_email: 'pmartinez@empresa.cl', cliente_telefono: '+56911223344', tipo_cliente: 'B2B Pyme', sku: 'POSAV-001', descripcion_items: '10x Posavasos Set x4', cantidad: 10, subtotal: 79900, costo_envio: 5990, descuento: 5000, total: 80890, medio_pago: 'Crédito', estado: 'Listo para Despacho', ciudad: 'Santiago', courier: 'Starken' },
    { numero_pedido: 'PW-006', fecha: '2026-04-06', canal: 'MercadoLibre', cliente_nombre: 'Francisca López', cliente_email: 'flopez@gmail.com', cliente_telefono: '+56934567890', tipo_cliente: 'B2C Individual', sku: 'MACE-001', descripcion_items: '2x Macetero Ecológico', cantidad: 2, subtotal: 11980, costo_envio: 3990, descuento: 0, total: 15970, medio_pago: 'MercadoPago', estado: 'Confirmado', ciudad: 'Temuco', courier: 'Correos Chile' },
    { numero_pedido: 'PW-007', fecha: '2026-04-07', canal: 'Instagram', cliente_nombre: 'Daniela Soto', cliente_email: 'dani.soto@gmail.com', cliente_telefono: '+56967890123', tipo_cliente: 'B2C Individual', sku: 'CACH-001', descripcion_items: '1x Pack Cachos (6u) personalizado', cantidad: 6, subtotal: 25990, costo_envio: 3990, descuento: 0, total: 29980, medio_pago: 'WebPay', estado: 'Entregado', ciudad: 'Santiago', courier: 'Retiro en Tienda', requiere_personalizacion: true, texto_personalizacion: 'Regalo familia', calificacion_cliente: 5 },
    { numero_pedido: 'PW-008', fecha: '2026-04-08', canal: 'Web Propia', cliente_nombre: 'Roberto Fuentes', cliente_email: 'rfuentes@gmail.com', cliente_telefono: '+56978901234', tipo_cliente: 'B2C Individual', sku: 'SONB-001', descripcion_items: '1x Soporte Notebook PEYU', cantidad: 1, subtotal: 9990, costo_envio: 3990, descuento: 0, total: 13980, medio_pago: 'Débito', estado: 'Nuevo', ciudad: 'La Serena', courier: 'Pendiente' },
    { numero_pedido: 'PW-009', fecha: '2026-04-09', canal: 'WhatsApp', cliente_nombre: 'Regalos Empresariales SA', cliente_email: 'ventas@regalos.cl', cliente_telefono: '+56222556677', tipo_cliente: 'B2B Corporativo', sku: 'LLAV-001', descripcion_items: '100x Llavero Soporte Celular con logo corporativo', cantidad: 100, subtotal: 399000, costo_envio: 0, descuento: 50000, total: 349000, medio_pago: 'Transferencia', estado: 'Confirmado', ciudad: 'Santiago', courier: 'BlueExpress', requiere_personalizacion: true, logo_recibido: false },
    { numero_pedido: 'PW-010', fecha: '2026-04-10', canal: 'Shopify', cliente_nombre: 'Valentina Herrera', cliente_email: 'vale.herrera@gmail.com', cliente_telefono: '+56956789012', tipo_cliente: 'B2C Individual', sku: 'SOPC-001', descripcion_items: '1x Soporte Celular + 1x Posavasos', cantidad: 2, subtotal: 14980, costo_envio: 3990, descuento: 0, total: 18970, medio_pago: 'Crédito', estado: 'Nuevo', ciudad: 'Antofagasta', courier: 'Pendiente' },
  ];

  await base44.asServiceRole.entities.PedidoWeb.bulkCreate(pedidos);

  return Response.json({ ok: true, creados: pedidos.length });
});