/**
 * Catálogo REAL de canales de marketing para PEYU.
 * Basado en los conectores OAuth disponibles en Base44 (verificado con get_connectors_info).
 * Los scopes listados son EXACTAMENTE los que Base44 acepta — cualquier otro será rechazado.
 */

export const CHANNELS = {
  // ============ NATIVOS OAUTH 1-CLIC ============
  ready: [
    {
      id: 'linkedin',
      integration_type: 'linkedin',
      name: 'LinkedIn',
      subtitle: 'Company Page + Ads',
      icon: '💼',
      color: 'from-blue-600 to-blue-800',
      caps: [
        'Publicar en Company Page',
        'Lead Gen Forms',
        'Campaign Manager (Ads)',
        'Analytics orgánico + paid',
      ],
      scopes: [
        'openid',
        'profile',
        'email',
        'w_member_social',
        'w_organization_social',
        'r_organization_social',
        'r_ads',
        'r_ads_reporting',
        'rw_ads',
      ],
      scopesLabel: 'w_organization_social · rw_ads · r_ads_reporting',
      docs: 'https://learn.microsoft.com/en-us/linkedin/marketing/',
      webhooks: false,
      ready: true,
    },
    {
      id: 'tiktok',
      integration_type: 'tiktok',
      name: 'TikTok',
      subtitle: 'Business Account',
      icon: '🎵',
      color: 'from-gray-900 via-pink-500 to-cyan-400',
      caps: [
        'Stats de perfil (followers, likes)',
        'Listado de videos públicos',
        'Info de bio y verificación',
      ],
      scopes: [
        'user.info.basic',
        'user.info.profile',
        'user.info.stats',
        'video.list',
      ],
      scopesLabel: 'user.info.stats · video.list',
      docs: 'https://developers.tiktok.com/doc/tiktok-api-v2-get-user-info/',
      webhooks: false,
      ready: true,
      warning:
        'Solo lectura. La publicación requiere TikTok Content Posting API (requiere aprobación separada de TikTok, no soportado aún por Base44).',
    },
    {
      id: 'google_analytics',
      integration_type: 'google_analytics',
      name: 'Google Analytics 4',
      subtitle: 'peyuchile.cl',
      icon: '📊',
      color: 'from-orange-500 to-yellow-500',
      caps: [
        'Tráfico web en tiempo real',
        'Conversiones + atribución',
        'Audiencias y eventos',
        'Revenue por canal',
      ],
      scopes: [
        'https://www.googleapis.com/auth/analytics.readonly',
      ],
      scopesLabel: 'analytics.readonly',
      docs: 'https://developers.google.com/analytics/devguides/reporting/data/v1',
      webhooks: false,
      ready: true,
    },
    {
      id: 'gmail',
      integration_type: 'gmail',
      name: 'Gmail',
      subtitle: 'ventas@peyuchile.cl',
      icon: '✉️',
      color: 'from-red-500 to-red-700',
      caps: [
        'Envío de newsletters y campañas',
        'Respuestas automáticas',
        'Webhook: nuevos emails en tiempo real',
        'Lectura con etiquetas',
      ],
      scopes: [
        'https://www.googleapis.com/auth/gmail.send',
        'https://www.googleapis.com/auth/gmail.readonly',
      ],
      scopesLabel: 'gmail.send · gmail.readonly',
      docs: 'https://developers.google.com/gmail/api',
      webhooks: true,
      webhookEvents: ['mailbox (nuevos mensajes en tiempo real)'],
      ready: true,
    },
    {
      id: 'googledrive',
      integration_type: 'googledrive',
      name: 'Google Drive',
      subtitle: 'Biblioteca de creatividades',
      icon: '📁',
      color: 'from-green-500 to-blue-500',
      caps: [
        'Guardar assets generados por IA',
        'Compartir briefs con cliente',
        'Watch de archivos (webhook)',
      ],
      scopes: [
        'https://www.googleapis.com/auth/drive.file',
      ],
      scopesLabel: 'drive.file (archivos creados por la app)',
      docs: 'https://developers.google.com/drive/api/v3/about-files',
      webhooks: true,
      webhookEvents: ['changes', 'file.update', 'file.trash'],
      ready: true,
      warning:
        'Scope limitado a drive.file: solo podemos acceder a archivos creados por PEYU o seleccionados vía Picker. No podemos listar toda tu Drive.',
    },
    {
      id: 'googlesheets',
      integration_type: 'googlesheets',
      name: 'Google Sheets',
      subtitle: 'Reportes de marketing',
      icon: '📈',
      color: 'from-emerald-500 to-green-600',
      caps: [
        'Exportar métricas consolidadas',
        'Dashboards compartidos',
        'Sync automático de KPIs',
      ],
      scopesLabel: 'spreadsheets',
      docs: 'https://developers.google.com/sheets/api',
      webhooks: false,
      ready: true,
    },
  ],

  // ============ REQUIEREN OAUTH APP CUSTOM ============
  custom: [
    {
      id: 'meta',
      name: 'Meta Business (Instagram + Facebook)',
      subtitle: 'Instagram Graph + Marketing API',
      icon: '📸',
      color: 'from-pink-500 via-purple-500 to-blue-600',
      caps: [
        'Publicar Feed / Reels / Stories',
        'Instagram Shopping',
        'FB Ads (Marketing API)',
        'Messenger / DM automation',
      ],
      docs: 'https://developers.facebook.com/docs/instagram-platform/',
      dashUrl: 'https://developers.facebook.com/apps/',
      setupTime: '~30 min',
      setupSteps: [
        'Crea una app en Meta for Developers',
        'Añade productos: "Instagram Graph API" + "Marketing API"',
        'Vincula tu Business Manager y cuenta IG Profesional',
        'Copia App ID + App Secret',
        'Solicita App Review para ir a producción',
      ],
    },
    {
      id: 'google_ads',
      name: 'Google Ads',
      subtitle: 'Search · PMax · Shopping',
      icon: '🎯',
      color: 'from-blue-500 to-green-500',
      caps: [
        'Campañas Search / PMax / Shopping',
        'Gestión de keywords + bids',
        'Reportes de conversión',
        'Audience Manager',
      ],
      docs: 'https://developers.google.com/google-ads/api/docs/start',
      dashUrl: 'https://ads.google.com/aw/apicenter',
      setupTime: '1-3 días hábiles',
      setupSteps: [
        'En tu cuenta Google Ads → API Center → solicitar Developer Token',
        'Crear OAuth Client ID en Google Cloud Console',
        'Esperar aprobación del developer token (1-3 días)',
        'Configurar login-customer-id del manager MCC',
      ],
    },
    {
      id: 'youtube',
      name: 'YouTube',
      subtitle: 'Canal PEYU',
      icon: '▶️',
      color: 'from-red-500 to-red-700',
      caps: [
        'Upload de videos y Shorts',
        'YouTube Analytics',
        'Moderación de comentarios',
        'Playlists dinámicas',
      ],
      docs: 'https://developers.google.com/youtube/v3',
      dashUrl: 'https://console.cloud.google.com/apis/library/youtube.googleapis.com',
      setupTime: '~15 min',
      setupSteps: [
        'Habilitar YouTube Data API v3 en Google Cloud Console',
        'Crear OAuth 2.0 Client ID',
        'Verificación obligatoria para > 100 uploads/día',
      ],
    },
    {
      id: 'pinterest',
      name: 'Pinterest Business',
      subtitle: 'Pins + Shopping Ads',
      icon: '📌',
      color: 'from-red-500 to-pink-600',
      caps: [
        'Publicar Pins + Video Pins',
        'Catálogo Shopping',
        'Shopping Ads + Analytics',
      ],
      docs: 'https://developers.pinterest.com/docs/api/v5/',
      dashUrl: 'https://developers.pinterest.com/apps/',
      setupTime: '~20 min',
      setupSteps: [
        'Crear cuenta en Pinterest Developer Portal',
        'Registrar app y activar Content API + Ads API',
        'Configurar redirect URI del callback OAuth',
      ],
    },
  ],

  // ============ SOPORTE NATIVO BASE44 PARA CRM + SOPORTE ============
  crm: [
    {
      id: 'hubspot',
      integration_type: 'hubspot',
      name: 'HubSpot',
      subtitle: 'CRM + Marketing Hub',
      icon: '🧲',
      color: 'from-orange-500 to-red-500',
      caps: [
        'Sync de contactos B2B',
        'Lifecycle stages',
        'Automatizaciones de email',
        'Deal pipeline',
      ],
      scopesLabel: 'crm.objects.contacts · crm.objects.deals',
      docs: 'https://developers.hubspot.com/docs/api/overview',
      webhooks: true,
      ready: true,
    },
    {
      id: 'slackbot',
      integration_type: 'slackbot',
      name: 'Slack (alertas)',
      subtitle: 'Canal #marketing',
      icon: '💬',
      color: 'from-purple-500 to-indigo-600',
      caps: [
        'Alertas de campañas en vivo',
        'Aprobaciones de posts',
        'Reportes diarios automáticos',
      ],
      scopesLabel: 'chat:write · channels:read',
      docs: 'https://api.slack.com/apis',
      webhooks: true,
      ready: true,
    },
    {
      id: 'notion',
      integration_type: 'notion',
      name: 'Notion',
      subtitle: 'Plan de contenidos',
      icon: '📝',
      color: 'from-gray-800 to-gray-900',
      caps: [
        'Calendario editorial sincronizado',
        'Briefs de campañas',
        'Base de conocimiento IA',
      ],
      scopesLabel: 'read_content · update_content · insert_content',
      docs: 'https://developers.notion.com/',
      webhooks: false,
      ready: true,
    },
  ],

  // ============ ROADMAP ============
  soon: [
    { id: 'threads', name: 'Threads', icon: '🧵', note: 'API aún limitada por Meta' },
    { id: 'twitter', name: 'X / Twitter', icon: '𝕏', note: 'API v2 requiere plan de pago ($100+/mes)' },
    { id: 'whatsapp_cloud', name: 'WhatsApp Business API', icon: '💚', note: 'Meta Cloud API — requiere verificación de negocio + número dedicado' },
    { id: 'mailchimp', name: 'Mailchimp', icon: '🐵', note: 'Evaluando para newsletter masivo' },
  ],
};